language: cpp
sudo: required
dist: bionic
os: linux
compiler: g++

notifications:
    email: false

addons:
  apt:
    update: true
    packages:
      - libusb-1.0-0-dev

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cmake --version

script: ./build.sh

env:
  global:
    - LC_ALL="en_US.UTF-8"
